# Generated by Django 4.1.3 on 2022-11-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(blank=True, max_length=120, null=True)),
                ("name", models.CharField(blank=True, max_length=240, null=True)),
                ("password", models.TextField()),
            ],
        ),
    ]
