# Generated by Django 4.1.3 on 2022-12-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securepassword",
            name="group",
        ),
        migrations.AddField(
            model_name="group",
            name="password",
            field=models.ManyToManyField(
                blank=True, related_name="group_password", to="base.securepassword"
            ),
        ),
    ]
